[package]
name = "notification-service"
version = "0.1.0"
edition = "2024"

[dependencies]
proto-hub = { path = "../proto-hub" }
tonic.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
# Крейт для работы с Kafka
rdkafka = { version = "0.39", features = ["tokio"] }
