[package]
name = "auth-service"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.5.3"
hex.workspace = true 
tonic.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
sea-orm.workspace = true
tonic-reflection.workspace = true
redis.workspace = true
proto-hub = { path = "../crates/proto-hub" }
entities = { path = "../crates/entities" }
utils = { path = "../crates/utils" }