[package]
name = "tracking-service"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono.workspace = true
tonic.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
sea-orm.workspace = true
proto-hub = { path = "../proto-hub" }
entities = { path = "../entities" }
utils = { path = "../utils" }